# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Personal Portfolio
subtitle: >- # this means to ignore newlines until "baseurl:"
  A website to tell people a little bit about myself.
name: Joshua Hamilton-Brown
email: me@joshuarhb.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my personal portfolio. I want to use this website to display my work and skills for people to get to know me better.
baseurl: ""
url: "https://joshuarhb.com"

# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

permalink: pretty

minimal_mistakes_skin: "mint" # Choose a skin for the theme


author:
  name: "Joshua Hamilton-Brown"
  avatar: "/assets/images/avatar.png" # Path to your avatar
  bio: "Software Engineer"
  location: "Tallinn, Estonia"
  email: "me@joshuarhb.com"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/joshuarhb"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/joshuarhb"
    - label: "Bluesky"
      icon: "fab fa-bluesky"
      url: "https://bsky.app/profile/joshuarhb.com"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
