name: Deploy Jekyll Site

on:
  push:
    branches: [ main ] # Trigger on pushes to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1 # Match your Jekyll-compatible Ruby version
          bundler-cache: true

      - name: Navigate to Jekyll Subdirectory
        run: cd joshuarhb.github.io # Replace with your subdirectory name

      - name: Install Dependencies
        run: bundle install

      - name: Build with Jekyll
        run: bundle exec jekyll build --destination ../_site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site # Built files are in root/_site
          publish_branch: gh-pages # Deploy to gh-pages branch